name: Build PyCom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper (if missing)
        run: |
          if [ ! -f ./gradlew ]; then
            gradle wrapper --gradle-version 8.2
            chmod +x ./gradlew
          fi

      - name: Build with Gradle
        run: ./gradlew build
