









name: Build PyCom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper (force 8.2)
  run: |
    rm -rf gradle gradlew gradlew.bat
    mkdir -p gradle/wrapper
    echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
    echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
    echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.2-all.zip" >> gradle/wrapper/gradle-wrapper.properties
    echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
    echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
    curl -sLo gradlew https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradlew
    chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
