name: Build PyCom (Gradle + Chaquopy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle (if wrapper missing)
        run: |
          if [ ! -f ./gradlew ]; then
            echo "⚙️ Gradle wrapper not found — generating..."
            gradle wrapper --gradle-version 7.5.1
            chmod +x ./gradlew
          fi

      - name: Grant execution permission for Gradle wrapper
        run: chmod +x ./gradlew || true

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyCom-APK
          path: app/build/outputs/apk/debug/*.apk
