name: Build PyCom (Gradle 7.5.1 + Chaquopy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Gradle 7.5.1
        run: |
          echo "⬇️ Downloading Gradle 7.5.1..."
          curl -sLo gradle-7.5.1-bin.zip https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
          unzip -q gradle-7.5.1-bin.zip
          echo "GRADLE_HOME=$(pwd)/gradle-7.5.1" >> $GITHUB_ENV
          echo "$(pwd)/gradle-7.5.1/bin" >> $GITHUB_PATH

      - name: Generate Gradle wrapper (v7.5.1)
        run: |
          gradle wrapper --gradle-version 7.5.1
          chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyCom-APK
          path: app/build/outputs/apk/debug/*.apk
